[2022-02-14 10:13:59,810] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: credit_card_dag.etl manual__2022-02-14T16:12:54.533922+00:00 [queued]>
[2022-02-14 10:13:59,821] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: credit_card_dag.etl manual__2022-02-14T16:12:54.533922+00:00 [queued]>
[2022-02-14 10:13:59,821] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-14 10:13:59,821] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-14 10:13:59,821] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-14 10:13:59,843] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): etl> on 2022-02-14 16:12:54.533922+00:00
[2022-02-14 10:13:59,847] {standard_task_runner.py:52} INFO - Started process 6399 to run task
[2022-02-14 10:13:59,852] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'credit_card_dag', 'etl', 'manual__2022-02-14T16:12:54.533922+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpmtvgm96g', '--error-file', '/tmp/tmpt5ly5_sq']
[2022-02-14 10:13:59,853] {standard_task_runner.py:77} INFO - Job 15: Subtask etl
[2022-02-14 10:13:59,914] {logging_mixin.py:109} INFO - Running <TaskInstance: credit_card_dag.etl manual__2022-02-14T16:12:54.533922+00:00 [running]> on host LAPTOP-GCF7F7F0.localdomain
[2022-02-14 10:13:59,953] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=credit_card_dag
AIRFLOW_CTX_TASK_ID=etl
AIRFLOW_CTX_EXECUTION_DATE=2022-02-14T16:12:54.533922+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-14T16:12:54.533922+00:00
[2022-02-14 10:13:59,958] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/astrid/airflow/dags/pipeline.py", line 13, in extract_validate_load
    df = pd.read_excel("app_data.xlsx")
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1419, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 524, in __init__
    import_optional_dependency("openpyxl")
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-02-14 10:13:59,966] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=credit_card_dag, task_id=etl, execution_date=20220214T161254, start_date=20220214T161359, end_date=20220214T161359
[2022-02-14 10:13:59,988] {standard_task_runner.py:89} ERROR - Failed to execute job 15 for task etl
Traceback (most recent call last):
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/astrid/airflow/dags/pipeline.py", line 13, in extract_validate_load
    df = pd.read_excel("app_data.xlsx")
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 457, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1419, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 524, in __init__
    import_optional_dependency("openpyxl")
  File "/home/astrid/challenge-env/lib/python3.8/site-packages/pandas/compat/_optional.py", line 129, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-02-14 10:14:00,025] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-14 10:14:00,042] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
